sudo: required
before_install:
  - sudo apt-get install libao-dev
  - sudo apt-get install libcurl4-openssl-dev
  - sudo apt-get install zlib1g-dev
  - sudo apt-get install libboost-all-dev
  - sudo apt-get install -y libuv-dev
  
# Enable C++ support
language: cpp

# Compiler selection
compiler:
  - gcc
  
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-6
      - g++-6
      - cmake

# Build steps
script:
  - sudo ln -s /usr/bin/gcc-6 /usr/local/bin/gcc
  - sudo ln -s /usr/bin/g++-6 /usr/local/bin/g++
  - export CC=/usr/bin/gcc-6
  - export CXX=/usr/bin/g++-6
  - gcc -v && g++ -v && cmake --version
  - cd .. && mkdir release
  - cd release
  - cmake .. -DCMAKE_BUILD_TYPE=release cmake -DLIBUV_ROOT_DIR=/usr/include/libuv -DOPENSSL_ROOT_DIR=/usr/include/ssl -DBOOST_ROOT=/usr/include/boost